{{- if (not .Values.bot.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bot-config
data:
  {{- range $key, $val := .Values.bot.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
