{{- if (not .Values.bot.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server-secret
type: Opaque
data:
  {{- range $key, $val := .Values.server.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
