{{- if (not .Values.server.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-server-config
data:
  {{- range $key, $val := .Values.server.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
